### ISSUE TITLE
Maven package failure

### ISSUE THREAD

**Issue by chipmccormick** [juanpabloprado/dw-multipart#1]
When I run 'maven package' I get the following. I'm running Maven 3.2.1

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project dw-multipart: Compilation failure: Compilation failure:
[ERROR] /D:/hg/MC/dw-multipart-master/dw-multipart-master/src/main/java/com/juanpabloprado/dw/examples/resources/FileResource.java:[5,58] package com.sun.xml.internal.messaging.saaj.packaging.mime does not exist
[ERROR] /D:/hg/MC/dw-multipart-master/dw-multipart-master/src/main/java/com/juanpabloprado/dw/examples/resources/FileResource.java:[26,82] cannot find symbol
[ERROR] symbol:   class MessagingException
[ERROR] location: class com.juanpabloprado.dw.examples.resources.FileResource

**Comment by juanpabloprado** [comment]
![2015-08-03_16-39-50](https://cloud.githubusercontent.com/assets/9583719/9048511/61e9bc32-39ff-11e5-8cb9-041647229526.png)

I've removed the lines that were throwing that error, Anyhow you can still run it directly from IntelliJ, As a side note the project was made with Java 7, I'll rewrite it later for Java 8, In the meantime, hope it works for you.
